stages:
  - lint
  - build


services:
  - docker:24.0.5-dind

variables:
  TARGETARCH: "amd64"
  TARGETOS: "linux"
  CGO_ENABLED: "0"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

# Kubernetes runner uses this image as the base
default:
  image: ghcr.io/sarco3t/jenkins-go-agent:v0.0.3-1c89396
  before_script:
    - echo "Using TARGETARCH=$TARGETARCH TARGETOS=$TARGETOS"
    - echo "Build started on $(date)"

lint:
  stage: lint
  script:
    - golangci-lint run --timeout=5m

build:
  # image: docker:24
  stage: build
  script:
    - make image TARGETARCH=$TARGETARCH TARGETOS=$TARGETOS