stages:
  - lint
  - build


services:
  - docker:28.2.2-dind

variables:
  TARGETARCH: "amd64"
  TARGETOS: "linux"
  CGO_ENABLED: "0"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  GIT_DEPTH: 0 # just to reach out last tag
  DOCKER_BUILDKIT: 1

default:
  image: ghcr.io/sarco3t/jenkins-go-agent:v0.0.3-1c89396
  before_script:
    - echo "Using TARGETARCH=$TARGETARCH TARGETOS=$TARGETOS"
    - echo "Build started on $(date)"

lint:
  stage: lint
  script:
    - golangci-lint run --timeout=5m

build:
  # image: docker:24
  stage: build
  script:
    - make image TARGETARCH=$TARGETARCH TARGETOS=$TARGETOS