# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  registry: "ghcr.io"
  repository: sarco3t
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.3-2a10d0d"
  arch: amd64
  os: linux
# Regular environment variables
env:
  - name: "LOG_LEVEL"
    value: "debug"
  - name: "METRICS_HOST"
    value: ""
# Secret-based environment variables
secrets:
  - name: "kbot"
    env: "TELE_TOKEN"
    key: "token"
  - name: "kbot"
    env: "API_VERSION"
    key: "api_version"
