name: KBOT-RELEASE

on:
  push:
    tags:
      - v*


env:
  TARGETARCH: amd64
  TARGETOS: linux
  CGO_ENABLED: 0
  
jobs:
  cd:
    name: Helm Chart Update
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'
          cache: true

      - name: Set version
        run: |
          VERSION=$(git describe --tags --abbrev=0 | cut -c 2-)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: Update Helm chart
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml

      - name: Commit Helm chart changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add helm/values.yaml
          git commit -m "chore: update version to ${{ env.VERSION }}"
          git push

      - name: Cleanup
        run: make clean TARGETARCH=${{ env.TARGETARCH }}